### ISSUE TITLE
Other relevant documents 

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl.github.io#17]
There are a number of additional relevant documents we should consider migrating.  In particular I can think of: 
- Anything historical (advanced BioPerl, how Perl saved the human genome project, etc)
- installation-related docs
- Maintenance related

**Comment by bosborne** [comment]
Chris, if you don't mind I'm going to close this and make separate tickets for each. BTW, Advanced Bioperl is done, it is now a HOWTO.

**Comment by cjfields** [comment]
Works for me :+1:
