### ISSUE TITLE
Migrate Scrapbook pages

### ISSUE THREAD

**Issue by bosborne** [bioperl/bioperl.github.io#29]
There are a bunch of these, all with interesting code in them, could be merged into a single page, or HOWTO

**Comment by pcantalupo** [comment]
I think this is something I could do and am trying to think of the best way to go about it. Do you want to copy over all the content into a `scrapbook` folder? Or should I web scrape the wiki?

**Comment by bosborne** [comment]
I'm thinking this is easiest as a single file, not a collection of files that have to be listed in some second file. If you make a single Markdown or HTML file from all the pages in the Scrapbook category then I will move some of the items out of the FAQ into this single file. So the FAQ will be all advice, and this "scrapbook" file will be all code. We'll put a TOC on top, simply by setting its layout to "howto". If you want you can use the attached script, rename it to ".py".
[mw2md.txt](https://github.com/bioperl/bioperl.github.io/files/71306/mw2md.txt)

**Comment by pcantalupo** [comment]
Hi Brian,  I got a first draft of the scrapbook on branch [i29/scrapbook](https://github.com/bioperl/bioperl.github.io/tree/i29/scrapbook). Please take a look and let me know if this is what you had in mind. There are many formatting issues to fix which I'm currently working on.

**Comment by bosborne** [comment]
Yes, that's right. If we add a '##' or '###' to each section then a TOC will be added at the top.

**Comment by pcantalupo** [comment]
closing based on pull #31
