### ISSUE TITLE
bioperl.org wiki site is down

### ISSUE THREAD

**Issue by pcantalupo** [bioperl/bioperl.github.io#30]
http://www.bioperl.org/wiki/Main_Page has been down for at least a day. I get the following error when visiting the site:

```
Sorry! This site is experiencing technical difficulties.

Try waiting a few minutes and reloading.

(Can't contact the database server: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) (localhost))
```

**Comment by bosborne** [comment]
```
cd /obf/website-logs/
for log in *log; do sudo rm $log; sudo touch $log; done
sudo mysql_safe &
```

**Comment by pcantalupo** [comment]
Hi Brian,
Site is down again. I don't know how to log in nor know if I have authorization. Thank you

**Comment by bosborne** [comment]
Backup now.

**Comment by cjfields** [comment]
The amazon instance isn't very capable of running the public wikis.  This and the need to move the docs to something more flexible are the keys reason to move to github.  At some point we anticipate aliasing/redirecting bioperl.org to bioperl.github.io.

**Comment by bosborne** [comment]
Chris, 

Yes, I was going to bring up the DNS change.

A big question is when to switch over, and I think the answer has to do with “when we think all the relevant content has been moved” and “when we like or approve  the new site”.

So, let’s get started on those questions, or any other related questions. Chris, what are your thoughts?

BIO

**Comment by bosborne** [comment]
Works.

**Comment by cjfields** [comment]
Heh, @bosborne completely missed your last comment, apologies.  

I'm wondering whether we can redirect to the new site and somehow keep a link to the old wiki while it is still running.  Not a huge priority though

**Comment by bosborne** [comment]
Chris,

Any time. Since the search works the basic functionality is all in-place. I think all the documentation is taken care of.

Yes, I’d keep the Wiki running for sure, but bioperl.org would point to bioperl.github.io.

Brian O.
