### ISSUE TITLE
install instructions still mention “Build.PL”

### ISSUE THREAD

**Issue by MjelleLab** [bioperl/bioperl.github.io#49]
The Build.PL seems to be missing? I am inside the bioperl-live directory.

**Comment by carandraug** [comment]
Oh, I see. That website. I would recommend you use the README file on the distribution, which depending what you want to do, might then redirect you to the HACKING file.

Anyway, I moved this issue to the website repository, maybe someone can fix it? I am personally a fan of not having the same instructions repeated in many places, do I would just replace that page on the website with a link to the files on the bioperl distribution.

**Comment by bosborne** [comment]
Linked.

**Comment by carandraug** [comment]
Thaks for the fix @bosborne . But it remains a link for website only windows install instructions which is equally out of date. Maybe that should be removed too?

**Comment by bosborne** [comment]
Do we have up-to-date Windows installation instructions?

**Comment by carandraug** [comment]
> Do we have up-to-date Windows installation instructions?

What is so special about bioperl on windows that needs its separate instructions? What I see from INSTALL.WIN is that it is mainly instructions on installing different perls on windows and setting up mingw. I really don't think bioperl documentation is the place to keep such detailed information.

**Comment by bosborne** [comment]
I never use Windows, so I can't address any questions about that content. Should we just remove the INSTALL.WIN page?

**Comment by carandraug** [comment]
> Should we just remove the INSTALL.WIN page?

Fine with me.

**Comment by bosborne** [comment]
Done.
